"use client";

import { useMemo, useState } from "react";
import { getDownloadUrl } from "@/src/lib/actions/arsip";
import { Button } from "@/src/components/ui/button";
import { Input } from "@/src/components/ui/input";

type Archive = Awaited<ReturnType<typeof import("@/src/lib/actions/arsip").getArsipList>>[number];
type Course = Awaited<ReturnType<typeof import("@/src/lib/actions/arsip").getMataKuliahOptions>>[number];

export function ArsipBrowser({ arsip, mataKuliah }: { arsip: Archive[]; mataKuliah: Course[] }) {
  const [search, setSearch] = useState(""); const [course, setCourse] = useState("all"); const [year, setYear] = useState("all"); const [category, setCategory] = useState("all");
  const years = [...new Set(arsip.map((item) => item.tahun))].sort((a, b) => b - a);
  const filtered = useMemo(() => arsip.filter((item) => (!search || `${item.judul} ${item.dosen ?? ""} ${item.deskripsi ?? ""}`.toLowerCase().includes(search.toLowerCase())) && (course === "all" || item.mataKuliahId === course) && (year === "all" || String(item.tahun) === year) && (category === "all" || item.kategori === category)), [arsip, search, course, year, category]);
  return <section className="mt-8"><div className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-4"><Input placeholder="Cari judul atau dosen" value={search} onChange={(event) => setSearch(event.target.value)} /><select className="h-8 rounded-lg border border-slate-300 px-2 text-sm" value={course} onChange={(event) => setCourse(event.target.value)}><option value="all">Semua mata kuliah</option>{mataKuliah.map((item) => <option key={item.id} value={item.id}>{item.kode} · {item.nama}</option>)}</select><select className="h-8 rounded-lg border border-slate-300 px-2 text-sm" value={year} onChange={(event) => setYear(event.target.value)}><option value="all">Semua tahun</option>{years.map((item) => <option key={item} value={item}>{item}</option>)}</select><select className="h-8 rounded-lg border border-slate-300 px-2 text-sm" value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">Semua kategori</option><option value="SOAL">Soal</option><option value="MATERI">Materi</option></select></div><div className="mt-5 grid gap-4 md:grid-cols-2">{filtered.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><h2 className="font-semibold text-slate-900">{item.judul}</h2><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">{item.kategori}</span></div><p className="mt-2 text-sm text-slate-600">{item.mataKuliah.kode} · {item.mataKuliah.nama} · {item.tahun}</p>{item.dosen && <p className="mt-1 text-sm text-slate-500">Dosen: {item.dosen}</p>}<Button className="mt-5" variant="outline" onClick={async () => { const result = await getDownloadUrl(item.id); if (result) window.open(result.downloadUrl, "_blank", "noopener,noreferrer"); }}>Buka dokumen</Button></article>)}{filtered.length === 0 && <p className="col-span-full rounded-2xl border border-dashed border-slate-300 p-10 text-center text-slate-600">Tidak ada arsip yang sesuai.</p>}</div></section>;
}