// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[slug]" | "/admin" | "/admin/arsip" | "/admin/arsip/mata-kuliah" | "/admin/koperasi" | "/admin/mathquiz" | "/admin/mathquiz/[quizId]/soal" | "/admin/rama" | "/admin/rama/[submissionId]" | "/admin/rama/kategori" | "/admin/rama/semester" | "/admin/redirect-link" | "/arsip" | "/blog" | "/blog/[slug]" | "/divisi" | "/forgot-password" | "/koperasi" | "/login" | "/mathquiz" | "/mathquiz/[quizId]" | "/mathquiz/leaderboard" | "/rama" | "/register" | "/reset-password" | "/tentang-kami"
type AppRouteHandlerRoutes = "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[slug]": { "slug": string; }
  "/admin": {}
  "/admin/arsip": {}
  "/admin/arsip/mata-kuliah": {}
  "/admin/koperasi": {}
  "/admin/mathquiz": {}
  "/admin/mathquiz/[quizId]/soal": { "quizId": string; }
  "/admin/rama": {}
  "/admin/rama/[submissionId]": { "submissionId": string; }
  "/admin/rama/kategori": {}
  "/admin/rama/semester": {}
  "/admin/redirect-link": {}
  "/arsip": {}
  "/auth/callback": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/divisi": {}
  "/forgot-password": {}
  "/koperasi": {}
  "/login": {}
  "/mathquiz": {}
  "/mathquiz/[quizId]": { "quizId": string; }
  "/mathquiz/leaderboard": {}
  "/rama": {}
  "/register": {}
  "/reset-password": {}
  "/tentang-kami": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
